### ISSUE TITLE
您好，一直搞不清楚您env文件里面的NOTIFYURL和REFUND_NOTIFY_URL的区别

### ISSUE THREAD

**Issue by AiPacino** [fastwego/wxpay#1]
rt，应该去什么地方配置那？

**Comment by Ceelog** [comment]
支付结果：https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_7&index=3
退款结果：https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_16&index=11
